### ISSUE TITLE
"You have reached the maximum amount of Protections, 0."

### ISSUE THREAD

**Issue by PneumaticHeal** [JGSBroadcast/SafePet#1]
I just installed the plugin(Latest Version) on a 1.8.3 spigot server and have been met with the line of error in the title. No plugin conflicts I have noticed in the console and I have not touched the config yet.

**Comment by JGSBroadcast** [comment]
Do you have the config.yml configured properly?

**Comment by PneumaticHeal** [comment]
I did not touch the config file as I didnt think I would need to change it.

**Comment by daliena** [comment]
Same error received as well. Using PEX, added required permissions. Have not touched config - made sure that max number of protections is set to default number of 10. Then decided to make a change in hope that maybe it did not like the 10. Also tried it with worlds enabled set to false and set to true. No luck. Tried in unprotected land, as well as within WorldGuard region. Tried as OP and as Player... Tried on non-pets, like a cow, and I get a msg This type cannot be protected, was able to access some of the other commands so the functionality seems to work. Just max number of protections isnt :(. Config below:

use-enabled-worlds: true
enabled-worlds:
- world
- world_nether
- world_the_end
max-pets: 20
max-id-length: 26
auto-update: false
version: 1.2.1

A useful plugin - hoping to get it to work. Please let me know if any additional info I can provide to assist you.

**Comment by JGSBroadcast** [comment]
This issue has been fixed in SafePet v1.2.2! Download available here: http://dev.bukkit.org/bukkit-plugins/safepet/files/10-safe-pet-v1-2-2/

**Comment by daliena** [comment]
Swapped the jar and reloaded the plugin. Tested - all is working - thank you so much!!! :D
